Tagging of individual certificates/templates
paramsiddharth/rema pull request #54
Opened 2021-12-15 22:34 UTC by MitanshiKshatriya

Closes #51
Added tags field to Template Schema and Certificate Schema  
1. Certificate Schema
```
title: {
		type: String,
		default: 'Certificate'
	},
	tags:[String], // Added tags field
	template: {
		type: String,
		required: true
	},
````
2. Template Schema
```
....
tags:[String],
...
```

2021-12-27 17:46 UTC, paramsiddharth requested changes
Please make the suggested changes for a more consistent code style.

2021-12-27 17:46 UTC, paramsiddharth commented on src/models/certificate.js
> +	tags:[String],
```suggestion
	tags: [String],
```

2021-12-27 17:46 UTC, paramsiddharth commented on src/models/template.js
> +	tags:[String],
```suggestion
	tags: [String],
```

2021-12-27 19:50 UTC, MitanshiKshatriya commented
Ok got it

2021-12-28 19:59 UTC, MitanshiKshatriya commented
I have made the changes please check.

2022-01-05 08:37 UTC, paramsiddharth approved these changes
Looks good to me! We'll proceed with further updates pertaining to the usage of tags.

2022-01-05 10:11 UTC, merged